Repository redbox-mint/redbox-portal, pull requests merged in 2024-04, with the labels that each got.

#2081 Fixed: Workspace Dashboard Pagination
  angular/projects/researchdatabox/dashboard/src/app/dashboard.component.ts
Labels: bug

#2094 Record assign permission fix and more unit tests
  test/unit/services/RDMPService.test.js
  typescript/api/services/RDMPService.ts
Labels: bug, enhancement

#2106 improve local dev and ci
  .circleci/config.yml
  package.json
  support/development/prepareLocalDev.sh
  support/integration-testing/docker-compose.mocha.yml
  support/integration-testing/docker-compose.newman.yml
Labels: enhancement
