Repository redbox-mint/redbox-portal, pull requests merged in 2025-09, with the labels that each got.

#3074 Upgrade Node version to 24
  .circleci/config.yml
  .dockerignore
  .nvmrc
  Dockerfile
  angular/package-lock.json
  core/package-lock.json
  core/package.json
  dockerhub_deploy.sh
  dockerlocal_dev.sh
  package-lock.json
  removeDockerLogsPortal.sh
  support/development/prepareLocalDev.sh
  support/integration-testing/docker-compose.bruno.yml
  support/integration-testing/docker-compose.mocha.yml
  support/integration-testing/solr.in.sh
  support/integration-testing/travisRunIntegrationTest.sh
  support/unit-testing/angular/testAngular.sh
  support/unit-testing/angular/testDevAngular.sh
  test/bruno/package-lock.json
Labels: dependencies

#3297 Add Content Security Policy header with nonce
  angular-legacy/record_search/app/record_search.html
  angular-legacy/userProfile/app/userProfile.html
  angular/projects/researchdatabox/manage-roles/src/app/manage-roles.component.html
  angular/projects/researchdatabox/manage-users/src/app/manage-users.component.html
  api/policies/contentSecurityPolicy.js
  assets/styles/default-theme.scss
  config/policies.js
  config/webpack.js
  test/bruno/1 - REST API/7 - App Config/Get App Config.bru
  test/bruno/2 - AJAX calls/1 - Admin User Tests/Get App Config View - System Messages.bru
  views/default/default/admin/appconfig.ejs
  views/default/default/admin/deletedRecords.ejs
  views/default/default/admin/report.ejs
  views/default/default/admin/roles.ejs
  views/default/default/admin/users.ejs
  views/default/default/export/index.ejs
  views/default/default/layout.ejs
  views/default/default/layout/logo.ejs
  views/default/default/layout/menu.ejs
  views/default/default/listWorkspaces.ejs
  views/default/default/record/edit.ejs
  views/default/default/record/layout.ejs
  views/default/default/record/search.ejs
  views/default/default/record/view.ejs
  views/default/default/researcher/home.ejs
  views/default/default/user/local.ejs
  views/default/default/user/login.ejs
  views/default/default/user/profile.ejs
  views/default/rdmp/dashboard.ejs
  views/layout.ejs
  views/misc/ng2-apps.ejs
Labels: enhancement

#3313 Upgrade and migrate to Angular 20
  angular/angular.json
  angular/package-lock.json
  angular/package.json
  angular/projects/researchdatabox/app-config/src/app/app-config.component.html
  angular/projects/researchdatabox/app-config/src/app/app-config.component.ts
  angular/projects/researchdatabox/app-config/src/app/fieldTypes/array.type.ts
  angular/projects/researchdatabox/app-config/src/app/fieldTypes/object.type.ts
  angular/projects/researchdatabox/dashboard/src/app/dashboard.component.html
  angular/projects/researchdatabox/dashboard/src/app/sort/sort.component.html
  angular/projects/researchdatabox/deleted-records/src/app/deleted-records.component.html
  angular/projects/researchdatabox/export/src/app/export.component.html
  angular/projects/researchdatabox/export/src/app/export.component.ts
  angular/projects/researchdatabox/form/src/app/component/default-layout.component.ts
  angular/projects/researchdatabox/form/src/app/component/validation-summary.component.ts
  angular/projects/researchdatabox/form/src/app/form.component.html
  angular/projects/researchdatabox/form/src/app/form.component.ts
  angular/projects/researchdatabox/local-auth/src/app/local-auth.component.html
  angular/projects/researchdatabox/local-auth/src/app/local-auth.component.ts
  angular/projects/researchdatabox/manage-roles/src/app/manage-roles.component.html
  angular/projects/researchdatabox/manage-users/src/app/manage-users.component.html
  angular/projects/researchdatabox/manage-users/src/app/manage-users.component.spec.ts
  angular/projects/researchdatabox/portal-ng-common/package-lock.json
  angular/projects/researchdatabox/portal-ng-common/package.json
  angular/projects/researchdatabox/portal-ng-common/src/lib/csrf.interceptor.spec.ts
  angular/projects/researchdatabox/portal-ng-common/src/lib/header-sort.component.html
  angular/projects/researchdatabox/portal-ng-common/src/lib/record-table.component.html
  angular/projects/researchdatabox/portal-ng-common/src/lib/translation.service.ts
  angular/projects/researchdatabox/portal-ng-form-custom/package-lock.json
  angular/projects/researchdatabox/portal-ng-form-custom/package.json
  angular/projects/researchdatabox/report/src/app/report.component.html
  angular/tsconfig.json
  support/build/angular-i18next-index.d.ts
  support/build/compileProductionAngular.sh
  support/development/compileDevAngular.sh
Labels: enhancement, dependencies

#3298 Improve dynamic asset generation
  angular/projects/researchdatabox/form/src/app/component/base-wrapper.component.ts
  angular/projects/researchdatabox/form/src/app/component/default-layout.component.ts
  angular/projects/researchdatabox/form/src/app/component/groupfield.component.ts
  angular/projects/researchdatabox/form/src/app/component/repeatable.component.ts
  angular/projects/researchdatabox/form/src/app/component/save-button.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/tab.component.ts
  angular/projects/researchdatabox/form/src/app/component/validation-summary.component.spec.ts
  angular/projects/researchdatabox/form/src/app/form.component.ts
  angular/projects/researchdatabox/form/src/app/form.service.ts
  angular/projects/researchdatabox/form/src/app/helpers.spec.ts
  angular/projects/researchdatabox/portal-ng-common/src/lib/form/base.model.ts
  angular/projects/researchdatabox/portal-ng-common/src/lib/form/form-field-base.component.ts
  angular/projects/researchdatabox/portal-ng-common/src/lib/utility.service.ts
  config/dynamicasset.js
  config/routes.js
  form-config/default-1.0-draft.js
  package-lock.json
  package.json
  packages/sails-ng-common/src/config/form-config.model.ts
  packages/sails-ng-common/src/index.ts
  packages/sails-ng-common/src/template.model.ts
  packages/sails-ng-common/src/validation/helpers.ts
  packages/sails-ng-common/src/validation/index.ts
  packages/sails-ng-common/src/validation/validators.ts
  test/bruno/2 - AJAX calls/4 - Dynamic assets/Get dynamic apiClientConfig
  test/bruno/2 - AJAX calls/4 - Dynamic assets/Get dynamic branded adminReportTemplates.bru
  test/bruno/2 - AJAX calls/4 - Dynamic assets/Get dynamic branded apiClientConfig.bru
  test/bruno/2 - AJAX calls/4 - Dynamic assets/Get dynamic branded formDataValidations.bru
  test/bruno/2 - AJAX calls/4 - Dynamic assets/Get dynamic branded formExpressions.bru
  test/bruno/2 - AJAX calls/4 - Dynamic assets/Get dynamic branded formStructureValidations.bru
  test/bruno/2 - AJAX calls/4 - Dynamic assets/Get dynamic branded recordDashboardTemplates.bru
  test/unit/services/TemplateService.test.js
  typescript/api/additional/TemplateCompile.ts
  typescript/api/controllers/DynamicAssetController.ts
  typescript/api/services/FormRecordConsistencyService.ts
  typescript/api/services/FormsService.ts
  typescript/api/services/TemplateService.ts
  typescript/assets/default/default/js/client-script.ts
  typescript/config/validators.ts
  typescript/form-config/default-1.0-draft.ts
  views/default/default/record/view.ejs
  views/dynamicScriptAsset.ejs
  views/systemjs-config.ejs
Labels: enhancement

#3314 modernise dependabot config
  .github/dependabot.yml
Labels: enhancement, dependencies

#3327 Feature/ng19 forms migrate textarea
  angular/projects/researchdatabox/form/src/app/component/content.component.ts
  angular/projects/researchdatabox/form/src/app/component/default-layout.component.ts
  angular/projects/researchdatabox/form/src/app/component/repeatable.component.ts
  angular/projects/researchdatabox/form/src/app/component/save-button.component.ts
  angular/projects/researchdatabox/form/src/app/component/simpleinput.component.ts
  angular/projects/researchdatabox/form/src/app/component/textarea.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/textarea.component.ts
  angular/projects/researchdatabox/form/src/app/form.module.ts
  angular/projects/researchdatabox/form/src/app/static-comp-field.dictionary.ts
  angular/projects/researchdatabox/portal-ng-common/src/lib/form/form-field-base.component.ts
  form-config/default-1.0-draft.js
  packages/sails-ng-common/src/config/component/index.ts
  packages/sails-ng-common/src/config/component/simpleinput.model.ts
  packages/sails-ng-common/src/config/component/text.model.ts
  packages/sails-ng-common/src/config/component/textarea.model.ts
  packages/sails-ng-common/src/config/form-field-component.model.ts
  support/ng19-forms-migration/fieldComponentMap.js
  typescript/form-config/default-1.0-draft.ts
Labels: enhancement

#3395 Form and Component Lifecycle
  angular/projects/researchdatabox/form/src/app/component/default-layout.component.ts
  angular/projects/researchdatabox/form/src/app/component/save-button.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/save-button.component.ts
  angular/projects/researchdatabox/form/src/app/form.component.ts
  angular/projects/researchdatabox/portal-ng-common/src/lib/form/form-field-base.component.ts
  packages/sails-ng-common/src/status.model.ts
  support/specs/form-lifecycle/design.md
  support/specs/form-lifecycle/overview.md
Labels: enhancement

#3398 Feature ng19 forms migrate dropdown and selection component
  angular/projects/researchdatabox/form/src/app/component/checkbox-input.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/checkbox-input.component.ts
  angular/projects/researchdatabox/form/src/app/component/dropdown-input.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/dropdown-input.component.ts
  angular/projects/researchdatabox/form/src/app/component/radio-input.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/radio-input.component.ts
  angular/projects/researchdatabox/form/src/app/form.module.ts
  angular/projects/researchdatabox/form/src/app/static-comp-field.dictionary.ts
  form-config/default-1.0-draft.js
  packages/sails-ng-common/package-lock.json
  packages/sails-ng-common/src/config/component/checkbox-input.model.ts
  packages/sails-ng-common/src/config/component/dropdown-input.model.ts
  packages/sails-ng-common/src/config/component/index.ts
  packages/sails-ng-common/src/config/component/radio-input.model.ts
  support/ng19-forms-migration/fieldComponentMap.js
  typescript/form-config/default-1.0-draft.ts
Labels: enhancement
