Repository redbox-mint/redbox-portal, pull requests merged in 2025-07, with the labels that each got.

#3118 Improve tests
  angular/projects/researchdatabox/form/src/app/component/groupfield.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/repeatable.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/textfield.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/validation-summary.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/validation-summary.component.ts
  angular/projects/researchdatabox/form/src/app/form.component.spec.ts
  angular/projects/researchdatabox/form/src/app/form.component.ts
  angular/projects/researchdatabox/form/src/app/helpers.spec.ts
  angular/projects/researchdatabox/portal-ng-common/src/lib/form/form-field-base.component.ts
Labels: bug

#3135 Repeatable improvements
  angular/projects/researchdatabox/form/src/app/component/base-wrapper.component.ts
  angular/projects/researchdatabox/form/src/app/component/default-layout.component.ts
  angular/projects/researchdatabox/form/src/app/component/groupfield.component.ts
  angular/projects/researchdatabox/form/src/app/component/repeatable.component.spec.ts
  angular/projects/researchdatabox/form/src/app/component/repeatable.component.ts
  angular/projects/researchdatabox/form/src/app/form.component.ts
  angular/projects/researchdatabox/form/src/app/form.module.ts
  angular/projects/researchdatabox/form/src/app/static-comp-field.dictionary.ts
  angular/projects/researchdatabox/portal-ng-common/src/lib/form/form-field-base.component.ts
  typescript/form-config/default-1.0-draft.ts
Labels: bug, enhancement

#3157 Add sort parameter to named query config
  config/namedQuery.js
  core/src/model/storage/NamedQueryModel.ts
  typescript/api/controllers/webservice/ReportController.ts
  typescript/api/services/NamedQueryService.ts
  typescript/api/services/ReportsService.ts
  typescript/api/services/VocabService.ts
Labels: enhancement
